### ISSUE TITLE
Fix 3 -> main port

### ISSUE THREAD

**Issue by mjcarroll** [ignitionrobotics/ign-common#130]
Rebasing broke the diff, so this needs to be re-done, which will probably end with a force push to `main`

**Comment by mjcarroll** [comment]
Ref: ignitionrobotics/docs#108

**Comment by chapulina** [comment]
> force push to main

I don't think we need to be that strict. I'd be ok keeping the rebased commits there, and also merging forward the old ones. The code would remain the same, but the history would show duplicates of those commits. Considering we're building on top of a messy history from mercurial, I don't think this would be too bad at this point.

**Comment by mjcarroll** [comment]
Alright, I'll see what that looks like.

**Comment by mjcarroll** [comment]
Fixed by https://github.com/ignitionrobotics/ign-common/pull/145
