### ISSUE TITLE
👨‍🌾 Regression/Flake on VideoEncoderTest.Exists for ign-common3 on Windows

### ISSUE THREAD

**Issue by caguero** [ignitionrobotics/ign-common#148]
https://build.osrfoundation.org/job/ignition_common-ci-ign-common3-windows7-amd64/85/

Error message:

```
D:\Jenkins\workspace\ignition_common-ci-ign-common3-windows7-amd64\ws\ign-common\av\src\VideoEncoder_TEST.cc:71
Value of: common::exists(filePathMp4)
  Actual: true
Expected: false
```

Failing on December 29 for the first time.

**Comment by chapulina** [comment]
Testing a fix on https://github.com/ignitionrobotics/ign-common/pull/149

**Comment by peci1** [comment]
I think #125 fixed this issue while keeping the tests enabled, as opposed to #149 that disabled them.
