### ISSUE TITLE
SystemPaths::Find file crashs if callback is not set and file does not exist

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-common#17]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/issues/17)) by Shane Loretz (Bitbucket: [Shane Loretz](https://bitbucket.org/%7B656e3311-aad9-45a1-aaf7-b0ee0e84b287%7D/), GitHub: [sloretz](https://github.com/sloretz)).**

----------------------------------------
If `SystemPaths::FindFile()` is asked to find a non-existant file and the callback has not been set using `SystemPaths::SetFindFileCallback()`, the program will crash when it attempts to call the unset callback.

**Comment by chapulina** [comment]
I believe this has been solved, there are tests checking that it works:

https://github.com/ignitionrobotics/ign-common/blob/526c2aceb847dcdbfc2d25fc72457caaece03d3c/src/SystemPaths_TEST.cc#L129-L130
