### ISSUE TITLE
INTEGRATION_video_encoder fails on arm64, armhf debbuilds

### ISSUE THREAD

**Issue by scpeters** [ignitionrobotics/ign-common#180]
## Environment
* OS Version: Ubuntu 18.04, 20.04 and Debian Buster
* Source or binary build?

debbuild of 3.11.0

## Description
* Expected behavior: debbuild succeeds
* Actual behavior: debbuild fails due to failure of `INTEGRATION_video_encoder` test added in https://github.com/ignitionrobotics/ign-common/pull/125

~~~
The following tests FAILED:
	 43 - INTEGRATION_video_encoder (Failed)
Errors while running CTest
~~~

~~~
43/93 Test #43: INTEGRATION_video_encoder ...................***Failed    4.55 sec
Running main() from /var/lib/jenkins/workspace/ign-common3-debbuilder/build/ignition-common-3.11.0/test/gtest/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from EncoderDecoderTest
[ RUN      ] EncoderDecoderTest.DecodeEncodeDecode
[1;32m[Msg] [0m[1;32mCompatible SW encoder: [0m[1;32mlibx264[0m[1;32m[0m
[1;32m[Msg] [0m[1;32mUsing encoder [0m[1;32mlibx264[0m[1;32m[0m
[1;32m[Msg] [0m[1;32mFPS: [0m[1;32m42.2372[0m[1;32m[0m
[1;32m[Msg] [0m[1;32mFPS: [0m[1;32m40.6361[0m[1;32m[0m
/var/lib/jenkins/workspace/ign-common3-debbuilder/build/ignition-common-3.11.0/test/integration/video_encoder.cc:135: Failure
The difference between avgIntensity2 and avgIntensity is 1.8609066972724975, which exceeds 1.0, where
avgIntensity2 evaluates to 222.84679089026915,
avgIntensity evaluates to 224.70769758754165, and
1.0 evaluates to 1.
[  FAILED  ] EncoderDecoderTest.DecodeEncodeDecode (3003 ms)
[----------] 1 test from EncoderDecoderTest (3004 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (3008 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] EncoderDecoderTest.DecodeEncodeDecode

 1 FAILED TEST
~~~

## Steps to reproduce

1. Build on arm64 or armhf system
2. Run ctest

## Output

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-common3-debbuilder&build=896)](https://build.osrfoundation.org/job/ign-common3-debbuilder/896/) https://build.osrfoundation.org/job/ign-common3-debbuilder/896/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-common3-debbuilder&build=898)](https://build.osrfoundation.org/job/ign-common3-debbuilder/898/) https://build.osrfoundation.org/job/ign-common3-debbuilder/898/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-common3-debbuilder&build=901)](https://build.osrfoundation.org/job/ign-common3-debbuilder/901/) https://build.osrfoundation.org/job/ign-common3-debbuilder/901/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-common3-debbuilder&build=907)](https://build.osrfoundation.org/job/ign-common3-debbuilder/907/) https://build.osrfoundation.org/job/ign-common3-debbuilder/907/
* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign-common3-debbuilder&build=908)](https://build.osrfoundation.org/job/ign-common3-debbuilder/908/) https://build.osrfoundation.org/job/ign-common3-debbuilder/908/

**Comment by peci1** [comment]
Hmm... I wonder if doubling the intensity limit would be a non-flaky solution? The intensity tests were added mainly to prevent cases when the encoded video is completely wrong (all black, greenish film, stripes caused by wrong memory alignment)... so I think even raising the limit to 5 or 10 is okay (if I remember correctly, intensity here goes 0...255).
