### ISSUE TITLE
An API for getting temp path in Filesystem.hh

### ISSUE THREAD

**Issue by mahiuchun** [ignitionrobotics/ign-common#232]
## Desired behavior

`Filesystem.hh` should provide a function for getting a temp path suitable for the current operating system.

## Alternatives considered

N/A

## Implementation suggestion

Use the behavior as described in here:
https://www.boost.org/doc/libs/1_75_0/libs/filesystem/doc/reference.html#temp_directory_path
To cover both Linux/macOS and Windows.

## Additional context

`common::cwd()` is often used to "get a path to save a file" currently.
The problem with this approach is that CWD is not necessarily writable.
`av/src/VideoEncoder.cc` contains an example of this pattern.

**Comment by mjcarroll** [comment]
Since `ign-common` is now compiling with C++17, I think it would also be safe to use https://en.cppreference.com/w/cpp/filesystem/temp_directory_path
