### ISSUE TITLE
Upgrade macOS homebrew CI to >=10.15

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-common#249]
10.14 is going EOL soon, so we're going to require 10.15 or higher on `ign-common4` when https://github.com/ignitionrobotics/ign-common/pull/238 is merged.

## Desired behavior

CI automatically runs on 10.15 or higher.

## Alternatives considered

N/A

## Implementation suggestion

We'll need to manually upgrade all Jenkins nodes

**Comment by chapulina** [comment]
I believe this is done :heavy_check_mark:

**Comment by scpeters** [comment]
the only remaining machine is https://build.osrfoundation.org/computer/mac-ultron.mojave/

I've taken it offline to prepare for the upgrade
