### ISSUE TITLE
Inconsistent signed/unsigned integer type in SubMesh MaterialIndex

### ISSUE THREAD

**Issue by scpeters** [ignitionrobotics/ign-common#317]
As noted in https://github.com/ignitionrobotics/sdformat/pull/831/files#r816364549, the [SubMesh::MaterialIndex()](https://github.com/ignitionrobotics/ign-common/blob/ignition-common4_4.5.0/graphics/include/ignition/common/SubMesh.hh#L287-L289) accessor method and corresponding setter method both use `unsigned int` for the material index, but the value is stored internally as an `int` in [Material.cc](https://github.com/ignitionrobotics/ign-common/blob/ignition-common4_4.5.0/graphics/src/SubMesh.cc#L55) and explicitly uses a value of `-1` to represent an unsigned value.

We should consider using `std::optional<unsigned int>` for this API in ign-common5.

**Comment by chapulina** [comment]
> We should consider using std::optional<unsigned int> for this API in ign-common5.

That would be an elegant solution. A less elegant one, but that doesn't require a deprecation cycle and maintains API, would be to return something like `std::numeric_limits<unsigned int>::max()` for an invalid material.

**Comment by adlarkin** [comment]
I have a PR in progress that takes the `std::numeric_limits<unsigned int>::max()` approach for `ign-common5`. Should I continue down that path, or should I update the PR to use `std::optional`? I think that `std::optional` is the better option in this scenario and would prefer that approach, even if it requires tick tock.

**Comment by chapulina** [comment]
I'm ok with optional :+1: tick-tocking return values can be tricky though, we may need to change the getter's name

**Comment by adlarkin** [comment]
I opened a PR that uses `std::optional` in a new method and deprecates the current `MaterialIndex` method: #319

**Comment by mjcarroll** [comment]
Closed by #319
