### ISSUE TITLE
Fix doxygen

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-common#5]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/issues/5)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
Documentation generation is broken right now.

I started porting the documentation from ign-math in branch [doxygen](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/branches/compare/doxygen%0Ddefault#diff), but it's still incomplete.

**Comment by chapulina** [comment]
API docs look good now: https://ignitionrobotics.org/api/common/3.5/classes.html
