### ISSUE TITLE
bug in NodeAnimation.cc

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-common#54]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/issues/54)) by mingfei sun (Bitbucket: [mingfeisun](https://bitbucket.org/%7B1e5a944b-56e4-4808-b81d-d6de318feadc%7D/)).**

----------------------------------------
This line seems to be a bug: 

[https://github.com/ignitionrobotics/ign-common/blob/3c37ee48f32e9c468099d4d30ad22da82d1c33be/graphics/src/NodeAnimation.cc#L166](https://github.com/ignitionrobotics/ign-common/blob/3c37ee48f32e9c468099d4d30ad22da82d1c33be/graphics/src/NodeAnimation.cc#L166)

Function **FrameAt** is to interpolate a frame between _prevKey_ and _nextKey_. So the if should be like 

```c++
if (t < 0.0 || t > 1.0)
{
  ignerr << "Invalid time range\n";
  return math::Matrix4d();
}
```

**Comment by mjcarroll** [comment]
This was closed by [pull request #197](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-common/pull-requests/197)
