### ISSUE TITLE
Deprecate common::Time?

### ISSUE THREAD

**Issue by chapulina** [ignitionrobotics/ign-common#61]
With C++11, we could deprecate `common::Time` in favor of `std::chrono`.

That would impact some other libraries' public APIs, like `ign-sensors`.

**Comment by ahcorde** [comment]
- [ ] ign-gazebo https://github.com/ignitionrobotics/ign-gazebo/pull/309
 - [ ] ign-sensors https://github.com/ignitionrobotics/ign-sensors/pull/41
 - [ ] ign-common https://github.com/ignitionrobotics/ign-common/pull/90
